# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aea1f5e3360bb1e3b767c6e5c58603fee31f045ac62baecd9205436e7ceca5f0e2a19797bd672a4e7aef99623e76fac5d82d2010d24dde8c812803184e8c1e10

test:
  secret_key_base: 54ce443a34d515ace02a951d9710333edaa58027ad4a24675c6b58f44eb5fd76ffd8dff16d205ec294b17631f8cd2102f7ca0ca4729354e01173dc518a1c9786

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
